Repository Nagkomatla/SkillEd-Elearning-Platform.com, pull requests merged in 2025-08, with the labels that each got.

#8 Issue #5 resolved
  index.html
  script.js
  style.css
  subjects/computer_courses.html
  subjects/gate.html
  subjects/jee.html
  subjects/quiz.html
  subjects/quizStyle.css
  subjects/subjects.css
Labels: GSSoC25, Level 3 – Code Voyager

#16 Add Navigate to Top button with HTML, CSS, and JS
  index.html
  script.js
  style.css
  subjects/gate.html
  subjects/jee.html
  subjects/subjects.css
Labels: level1 - Bug Smasher, GSSoC25

#18 Improved Social Media Links Functionality and Styling In Footer
  images/icon/github.png
  images/icon/gmail.png
  images/icon/instagram.png
  images/icon/linkedin1.png
  images/icon/twitter.png
  index.html
  style.css
Labels: GSSoC25, Level 3 – Code Voyager

#24 Add animated count-up effect to stats section
  index.html
  script.js
Labels: GSSoC25, Level 1 – Rookie Coder

#28 Add a Code of Conduct to the Project #27
  CodeOfConduct.md
Labels: GSSoC25, Level 1 – Rookie Coder

#53 pr create automate message added
  .github/workflows/pr-create-automate-message.yml
Labels: level1 - Bug Smasher, GSSoC25
